global:
  identity:
    auth:
      enabled: false

identity:
  enabled: false

identityKeycloak:
  enabled: false

optimize:
  enabled: false

zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 1Gi # Keep PVC size as needed for data persistence

zeebeGateway:
  replicas: 1
  resources:
    requests:
      cpu: 100m # Significantly reduced
      memory: 128Mi # Significantly reduced
    limits:
      cpu: 250m
      memory: 256Mi

zeebeBroker:
  resources:
    requests:
      cpu: 250m # Reduced significantly; monitor performance closely
      memory: 512Mi # Reduced, but be cautious about going lower
    limits:
      cpu: 500m
      memory: 1Gi

connectors:
  enabled: true
  inbound:
    mode: disabled
  resources:
    requests:
      cpu: 100m # Further reduced
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

elasticsearch:
  master:
    replicaCount: 1
    resources:
      requests:
        cpu: 250m # Reduced significantly; monitor performance closely
        memory: 512Mi # Reduced significantly; monitor performance closely
      limits:
        cpu: 250m
        memory: 512Mi
    persistence:
      size: 1Gi
      # Choose ONE of the following persistence options:
      # storageClass: "standard" # For production
      # type: emptyDir # For Kind/testing (data loss)
      # enabled: false # For testing (no persistence)

operate:
  resources:
    requests:
      cpu: 300m # Reduced, monitor usage
      memory: 512Mi # Reduced, monitor usage
    limits:
      cpu: 1
      memory: 1Gi

tasklist:
  resources:
    requests:
      cpu: 200m # Reduced, monitor usage
      memory: 512Mi # Reduced, monitor usage
    limits:
      cpu: 500m
      memory: 1Gi
